### ISSUE TITLE
Code is never executed after a return statement is reached

### ISSUE THREAD

**Issue by Taym95** [wassim31/Decimal-to-BI-OCT-HEX#1]
https://github.com/wassim31/Decimal-to-BI-OCT-HEX/blob/3e870c8e1d17aee26a2ca67cfa557c2d040134f3/main.c#L65

You should free the memory then call return.

```
    // de-allocate the heap memory
    free(new_number);
    return 0;
```

**Comment by wassim31** [comment]
Can you explain this case specifically in memory ? if the return statement is reached the heap's allocated memory stays ?

**Comment by Taym95** [comment]
Any code after the return statement will not be executed, since you are freeing memory after the return statement `free(new_number)` will not be called, and allocated memory will stay!

**Comment by wassim31** [comment]
Issue fixed successfully ; you can check the last commit .
